### ISSUE TITLE
It's simply not working

### ISSUE THREAD

**Issue by 7ylxr9** [stefansundin/youtube-copy-annotations#1]
I am doing all the steps and it's not actually publishing the annotations on the new video. This is what Firebug looks like when I click Copy http://i.imgur.com/fTCRfwI.png?2. Publishing returns the normal 200 OK status. Why isn't it working now? Worked last week!

**Comment by stefansundin** [comment]
They might have changed something, I will take a look tonight. Thanks for reporting.

**Comment by stefansundin** [comment]
I just tested it, and it is still working for me.

**Comment by 7ylxr9** [comment]
I guess I'll have to find another way to copy annotations since this still won't work :(

**Comment by stefansundin** [comment]
Can you post the video you are trying to copy from? I will try exactly what
you are attempting to do if you can give me more information.

**Comment by 7ylxr9** [comment]
Well I run this channel (removed URL) and I use the same annotations from video to video changing out a couple links so maybe try one of those but it has to be one of the newer ones since I added an endscreen to the end with more annotations.

**Comment by stefansundin** [comment]
Okay, I think I fixed your issue. The XML contained a Card, which the script didn't expect. It now better removes unknown annotations. Let me know if it still doesn't work. Enjoy.

**Comment by 7ylxr9** [comment]
I'll try tomorrow, thanks!

**Comment by 7ylxr9** [comment]
Just tried it and it works! Thanks for helping :)

**Comment by kruin** [comment]
Hi,
As you can see ( https://www.youtube.com/watch?v=12tB3Su1hB8 ), I intensively use Mytube. Apparently, once installed, Mytube still performs great, that is: superb!
As a feature request: if available, please document the full Annotation schema. That would speed up my project. 
Regards,

Toon van Opstal
