### ISSUE TITLE
It's not working - Forbiden 403

### ISSUE THREAD

**Issue by phuclh** [stefansundin/youtube-copy-annotations#2]
I got this error when I copy and publish annotations. Please help me, thank you very much!!!!
http://i.imgur.com/ZlQ6Krx.png

**Comment by stefansundin** [comment]
Check if you are actually logged in on YouTube, try to copy a simpler annotation (maybe just a simple text annotation). See if there are unescaped ampersands in the XML.

If that doesn't work, please supply more information, maybe what video you are copying from, etc.

**Comment by phuclh** [comment]
Ok. I forgot logged in on YT :D.
