### ISSUE TITLE
I couldn't get the auth_token on my own any advice ?

### ISSUE THREAD

**Issue by devahmedraafat** [stefansundin/youtube-copy-annotations#3]

**Comment by stefansundin** [comment]
The userscript still works for me.

**Comment by devahmedraafat** [comment]
I want to generate my own chrome extension like yours but with more enhancements but i don't know how your userscript get the auth_token from the logged in user.

In your published extension at debug tab you were able to get refresh auth_token

**Comment by stefansundin** [comment]
All the code you need is in this file: https://github.com/stefansundin/youtube-copy-annotations/blob/gh-pages/youtube_auth_token.user.js
